# frdm-kl25z platform makefile

ifndef CONTIKI
  $(error CONTIKI not defined! You must specify where CONTIKI resides!)
endif

CONTIKI_TARGET_DIRS = . apps net dev

CONTIKI_TARGET_SOURCEFILES += contiki-frdm-main.c contiki-frdm-platform.c
CONTIKI_TARGET_SOURCEFILES += leds-arch.c node-id.c acc-sensor.c

CONTIKI_SOURCEFILES += $(CONTIKI_TARGET_SOURCEFILES)

ifeq ($(UIP_CONF_IPV6),1)
CFLAGS += -DWITH_UIP6=1
endif

CLEAN += *.frdm-kl25z

### Unless the example dictates otherwise, build with code size optimisations
ifndef SMALL
  SMALL = 1
endif

### Define cpu memory size
ifndef MEM_SIZE
	MEM_SIZE = 128
endif

CONTIKI_CPU=$(CONTIKI)/../cpu/kinetis/MKL25Z4
include $(CONTIKI_CPU)/Makefile.mkl25z4

MODULES += core/net core/net/ip core/net/ipv6 core/net/ipv4 core/net/mac \
           core/net/rime core/net/mac/contikimac core/net/rpl \
           dev/cc2520